---
- hosts: db1.rhpds.opentlc.com
  remote_user: root

  tasks:
  - name: ensure mariadb is at the latest version
    yum: name=mariadb state=latest
  - name: ensure that mariadb is started
    service: name=mariadb state=started
