- name: This sets up an mariadb database server
  hosts: db1.rhpds.opentlc.com
  tasks:
     - name: Install the mariadb rpm
       yum: name=mariadb-server mariadb       
     - name: start the mariadb service
       service: name=mariadb state=started     
